-- 데이터베이스 생성
CREATE DATABASE COLLAB;
USE COLLAB;


-- 사용자 계정 생성
CREATE USER 'kyubo'@'%' IDENTIFIED BY 'tn3718';
-- 데이터베이스의 권한을 생성한 계정에게 부여
GRANT ALL PRIVILEGES ON COLLAB.* TO 'kyubo'@'%';
-- 새로고침
FLUSH PRIVILEGES;




CREATE TABLE USER_ACCOUNT (
	ACCOUNT_ID				BIGINT					NOT NULL AUTO_INCREMENT COMMENT '사용자계정번호',
	ID						VARCHAR(20)				NOT NULL COMMENT '계정 아이디',
	PASSWORD				VARCHAR(255)			NOT NULL COMMENT '계정 비밀번호',
	EMAIL					VARCHAR(40)				NOT NULL COMMENT '이메일',
	NAME					VARCHAR(12)				NOT NULL COMMENT '이름',
	ENABLED					TINYINT(1)				NOT NULL COMMENT '계정 활성화여부',
	LOGIN_TYPE				VARCHAR(7)				NOT NULL COMMENT '계정 유형',
	CREATED_AT				DATETIME				NOT NULL COMMENT '가입일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '변경일자',
	PRIMARY KEY (ACCOUNT_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자계정테이블';




CREATE TABLE USER_ROLE (
	USER_ID					BIGINT					NOT NULL COMMENT '사용자계정번호(FK)',
	ROLE					VARCHAR(25) 			NOT NULL COMMENT '권한명',
	USED_AT					CHAR(1) 				NOT NULL COMMENT '권한 사용여부',
	CREATED_AT				DATETIME				NOT NULL COMMENT '권한등록일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '권한변경일자',
	FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자계정별 권한테이블';




CREATE TABLE USER_PROFILE (
	PROFILE_ID				BIGINT					NOT NULL AUTO_INCREMENT COMMENT '계정프로필번호',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자계정번호(FK)',
	PROFILE_IMG_NAME		VARCHAR(255)			NOT NULL COMMENT '계정 프로필 이미지명',
	PROFILE_IMG_URL			VARCHAR(255)			NOT NULL COMMENT '계정 프로필 이미지 경로',
	PROFILE_IMG_SIZE		BIGINT					NOT NULL COMMENT '계정 프로필 이미지 크기',
	INTRODUCTION			TEXT					NOT NULL COMMENT '프포필 소개글(소개가 없습니다.)',
	UNIV_NAME				VARCHAR(50)				NOT NULL COMMENT '출신 대학교명(선택안함)',
	CITY					VARCHAR(18)				NOT NULL COMMENT '거주중인 도시명(선택안함)',
	CREATED_AT				DATETIME				NOT NULL COMMENT '등록일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '변경일자',
	PRIMARY KEY (PROFILE_ID),
	FOREIGN KEY (USER_ID) REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '사용자 계정 프로필정보테이블';




CREATE TABLE TEAM (
	TEAM_ID					BIGINT					NOT NULL AUTO_INCREMENT COMMENT '팀번호',
	NAME 					VARCHAR(60)				NOT NULL COMMENT '팀명',
	INTRODUCTION			TEXT					NOT NULL COMMENT '팀소개글',
	CREATED_AT				DATETIME				NOT NULL COMMENT '팀정보 등록일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '팀정보 변경일자',
	DELETED_AT				CHAR(1)					NOT NULL DEFAULT 'N' COMMENT '삭제여부',
	PRIMARY KEY (TEAM_ID)
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀 정보테이블';




CREATE TABLE TEAM_USER (
	TEAM_ID					BIGINT					NOT NULL COMMENT '팀번호(FK)',
	USER_ID					BIGINT					NOT NULL COMMENT '사용자계정번호(FK)',
	IS_TEAM_LEADER			CHAR(1)					NOT NULL COMMENT '팀장여부',
	DEV_TYPE				CHAR(2)					NOT NULL COMMENT '주분야',
	CREATED_AT				DATETIME				NOT NULL COMMENT '등록일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '변경일자',
	FOREIGN KEY (TEAM_ID)	REFERENCES	TEAM (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID)	REFERENCES	USER_ACCOUNT (ACCOUNT_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '팀원테이블';




CREATE TABLE PROJECT (
	PROJECT_ID				BIGINT					NOT NULL AUTO_INCREMENT COMMENT '프로젝트번호',
	PROJECT_NAME			VARCHAR(100)			NOT NULL COMMENT '프로젝트명',
	PROJECT_TYPE			VARCHAR(15)				NOT NULL COMMENT '프로젝트유형',
	TEAM_ID					BIGINT					NOT NULL COMMENT '프로젝트팀번호(FK)',
	USER_ID					BIGINT					NOT NULL COMMENT '프로젝트담당자 계정번호(FK)',
	INTRODUCTION			TEXT					NOT NULL COMMENT '프로젝트 소개글',
	START_DATE				DATETIME				NOT NULL COMMENT '시작일자',
	END_DATE				DATETIME				NOT NULL COMMENT '종료일자',
	PROJECT_STATUS			VARCHAR(10)				NOT NULL COMMENT '프로젝트 상태',
	CREATED_AT				DATETIME				NOT NULL COMMENT '프로젝트정보등록일자',
	UPDATED_AT				DATETIME				NOT NULL COMMENT '프로젝트정보변경일자',
	PRIMARY KEY (PROJECT_ID),
	FOREIGN KEY (TEAM_ID)	REFERENCES TEAM (TEAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (USER_ID)	REFERENCES USER_ACCOUNT (ACCOUNT_ID) ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '프로젝트정보테이블';




--CREATE TABLE TASK () ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '';


--CREATE TABLE PROJECT_TASK () ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '';


--CREATE TABLE PROJECT_TASK_USER () ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '';


--CREATE TABLE 테이블명 () ENGINE = INNODB DEFAULT CHARSET = UTF8MB4 COMMENT '';
*/